/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author javir
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Zona_Hawkins = new javax.swing.JPanel();
        ScrollPanel_Calle_Principal = new javax.swing.JScrollPane();
        ScrollPanel_Sotano_Byers = new javax.swing.JScrollPane();
        Panel_Radio_WSQK = new javax.swing.JPanel();
        ScrollPanel_Radio_WSQK = new javax.swing.JScrollPane();
        Cantidad_Sangre = new javax.swing.JTextField();
        Label_SANGRE = new javax.swing.JLabel();
        Imagen_Radio = new javax.swing.JLabel();
        HAWKINS = new javax.swing.JLabel();
        Calle_Principal = new javax.swing.JLabel();
        Sotano_Byers = new javax.swing.JLabel();
        Calle_Principal2 = new javax.swing.JLabel();
        Imagen_Hawkins = new javax.swing.JLabel();
        Imagen_Sotano = new javax.swing.JLabel();
        Panel_Zona_Portales = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                // Pon aquí el nombre exacto de tu imagen de fondo
                java.net.URL ruta = getClass().getResource("/Imagenes/Textura_Panel_Portal.png");
                if (ruta != null) {
                    java.awt.Image imagenFondo = new javax.swing.ImageIcon(ruta).getImage();
                    g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
                } else {
                    System.err.println("No se encontró la imagen del fondo");
                }
            }
        };
        PORTALES = new javax.swing.JLabel();
        Panel_Portal_Bosque = new javax.swing.JPanel();
        Entrada_1 = new javax.swing.JPanel();
        Dentro_Portal_1 = new javax.swing.JPanel();
        Salida_1 = new javax.swing.JPanel();
        Panel_Portal_Laboratorio = new javax.swing.JPanel();
        Entrada_2 = new javax.swing.JPanel();
        Dentro_Portal_2 = new javax.swing.JPanel();
        Salida_2 = new javax.swing.JPanel();
        Panel_Portal_Centro_Comercial = new javax.swing.JPanel();
        Entrada_3 = new javax.swing.JPanel();
        Dentro_Portal_3 = new javax.swing.JPanel();
        Salida_3 = new javax.swing.JPanel();
        Panel_Portal_Alcantarillado = new javax.swing.JPanel();
        Entrada_4 = new javax.swing.JPanel();
        Dentro_Portal_4 = new javax.swing.JPanel();
        Salida_4 = new javax.swing.JPanel();
        Panel_Zona_Upsidedown = new javax.swing.JPanel();
        UPSIDEDOWN = new javax.swing.JLabel();
        Bosque = new javax.swing.JLabel();
        Panel_Bosque = new javax.swing.JPanel();
        ScrollPanel_NiñosBosque = new javax.swing.JScrollPane();
        ScrollPanel_DemogorgonsBosque = new javax.swing.JScrollPane();
        Textura_Bosque = new javax.swing.JLabel();
        Laboratorio = new javax.swing.JLabel();
        Panel_Portal_Laboratorio1 = new javax.swing.JPanel();
        ScrollPanel_NiñosLaboratorio = new javax.swing.JScrollPane();
        ScrollPanel_DemogorgonsLaboratorio = new javax.swing.JScrollPane();
        Textura_Laboratorio = new javax.swing.JLabel();
        Centro_Comercial = new javax.swing.JLabel();
        Panel_Portal_Centro_Comercial1 = new javax.swing.JPanel();
        ScrollPanel_NiñosCentroComercial = new javax.swing.JScrollPane();
        ScrollPanel_DemogorgonsCentroComercial = new javax.swing.JScrollPane();
        Textura_CentroComercial = new javax.swing.JLabel();
        Alcantarillado = new javax.swing.JLabel();
        Panel_Portal_Alcantarillado1 = new javax.swing.JPanel();
        ScrollPanel_NiñosAlcantarillado = new javax.swing.JScrollPane();
        ScrollPanel_DemogorgonsAlcantarillado = new javax.swing.JScrollPane();
        Textura_Alcantarillado = new javax.swing.JLabel();
        Panel_Estadisticas = new javax.swing.JPanel();
        Niños_Capturados = new javax.swing.JTextField();
        Texto_Eventos = new javax.swing.JLabel();
        Demogorgon = new javax.swing.JLabel();
        Vecna = new javax.swing.JLabel();
        Texto_NIÑOS_CAPTURADOS = new javax.swing.JLabel();
        Texto_NIÑOS_CAPTURADOS1 = new javax.swing.JLabel();
        Texto_Principal = new javax.swing.JLabel();
        Boton_Pausa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Zona_Hawkins.setBackground(new java.awt.Color(204, 255, 204));
        Panel_Zona_Hawkins.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 3));
        Panel_Zona_Hawkins.setPreferredSize(new java.awt.Dimension(300, 500));

        ScrollPanel_Calle_Principal.setPreferredSize(new java.awt.Dimension(260, 110));

        ScrollPanel_Sotano_Byers.setPreferredSize(new java.awt.Dimension(260, 110));

        Panel_Radio_WSQK.setOpaque(false);

        Cantidad_Sangre.setEditable(false);
        Cantidad_Sangre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cantidad_Sangre.setText("0");
        Cantidad_Sangre.setPreferredSize(new java.awt.Dimension(60, 40));
        Cantidad_Sangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cantidad_SangreActionPerformed(evt);
            }
        });

        Label_SANGRE.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        Label_SANGRE.setForeground(new java.awt.Color(255, 0, 0));
        Label_SANGRE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_SANGRE.setText("SANGRE");
        Label_SANGRE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Label_SANGRE.setOpaque(true);

        Imagen_Radio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Textura_Radio.png"))); // NOI18N

        javax.swing.GroupLayout Panel_Radio_WSQKLayout = new javax.swing.GroupLayout(Panel_Radio_WSQK);
        Panel_Radio_WSQK.setLayout(Panel_Radio_WSQKLayout);
        Panel_Radio_WSQKLayout.setHorizontalGroup(
            Panel_Radio_WSQKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Radio_WSQKLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ScrollPanel_Radio_WSQK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Radio_WSQKLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(Cantidad_Sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Radio_WSQKLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(Label_SANGRE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Imagen_Radio)
        );
        Panel_Radio_WSQKLayout.setVerticalGroup(
            Panel_Radio_WSQKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Radio_WSQKLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ScrollPanel_Radio_WSQK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Radio_WSQKLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Cantidad_Sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Radio_WSQKLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Label_SANGRE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Imagen_Radio)
        );

        HAWKINS.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        HAWKINS.setText("HAWKINS");

        Calle_Principal.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Calle_Principal.setText("Calle Principal");

        Sotano_Byers.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Sotano_Byers.setText("Sotano Byers");

        Calle_Principal2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Calle_Principal2.setText("Radio WSQK");

        Imagen_Hawkins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cartel_Hawkins.jpg"))); // NOI18N

        Imagen_Sotano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Textura_Sotano.PNG"))); // NOI18N

        javax.swing.GroupLayout Panel_Zona_HawkinsLayout = new javax.swing.GroupLayout(Panel_Zona_Hawkins);
        Panel_Zona_Hawkins.setLayout(Panel_Zona_HawkinsLayout);
        Panel_Zona_HawkinsLayout.setHorizontalGroup(
            Panel_Zona_HawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(HAWKINS))
            .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Calle_Principal))
            .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ScrollPanel_Calle_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Imagen_Hawkins))
            .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Sotano_Byers))
            .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Panel_Zona_HawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(ScrollPanel_Sotano_Byers, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Imagen_Sotano)))
            .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Calle_Principal2))
            .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Panel_Radio_WSQK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_Zona_HawkinsLayout.setVerticalGroup(
            Panel_Zona_HawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(HAWKINS)
                .addGap(4, 4, 4)
                .addComponent(Calle_Principal)
                .addGap(9, 9, 9)
                .addGroup(Panel_Zona_HawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPanel_Calle_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Imagen_Hawkins, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(Sotano_Byers)
                .addGap(4, 4, 4)
                .addGroup(Panel_Zona_HawkinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Zona_HawkinsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ScrollPanel_Sotano_Byers, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Imagen_Sotano))
                .addGap(20, 20, 20)
                .addComponent(Calle_Principal2)
                .addGap(9, 9, 9)
                .addComponent(Panel_Radio_WSQK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_Zona_Portales.setBackground(new java.awt.Color(255, 153, 204));
        Panel_Zona_Portales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255), 3));
        Panel_Zona_Portales.setPreferredSize(new java.awt.Dimension(300, 500));

        PORTALES.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        PORTALES.setText("PORTALES");

        Panel_Portal_Bosque.setBackground(new java.awt.Color(156, 28, 156));
        Panel_Portal_Bosque.setOpaque(false);
        Panel_Portal_Bosque.setPreferredSize(new java.awt.Dimension(260, 100));

        javax.swing.GroupLayout Entrada_1Layout = new javax.swing.GroupLayout(Entrada_1);
        Entrada_1.setLayout(Entrada_1Layout);
        Entrada_1Layout.setHorizontalGroup(
            Entrada_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Entrada_1Layout.setVerticalGroup(
            Entrada_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Dentro_Portal_1Layout = new javax.swing.GroupLayout(Dentro_Portal_1);
        Dentro_Portal_1.setLayout(Dentro_Portal_1Layout);
        Dentro_Portal_1Layout.setHorizontalGroup(
            Dentro_Portal_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Dentro_Portal_1Layout.setVerticalGroup(
            Dentro_Portal_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Salida_1Layout = new javax.swing.GroupLayout(Salida_1);
        Salida_1.setLayout(Salida_1Layout);
        Salida_1Layout.setHorizontalGroup(
            Salida_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Salida_1Layout.setVerticalGroup(
            Salida_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_Portal_BosqueLayout = new javax.swing.GroupLayout(Panel_Portal_Bosque);
        Panel_Portal_Bosque.setLayout(Panel_Portal_BosqueLayout);
        Panel_Portal_BosqueLayout.setHorizontalGroup(
            Panel_Portal_BosqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Portal_BosqueLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Dentro_Portal_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Salida_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Entrada_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_Portal_BosqueLayout.setVerticalGroup(
            Panel_Portal_BosqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Portal_BosqueLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Dentro_Portal_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Portal_BosqueLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Salida_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Portal_BosqueLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Entrada_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_Portal_Laboratorio.setBackground(new java.awt.Color(156, 28, 156));
        Panel_Portal_Laboratorio.setOpaque(false);

        javax.swing.GroupLayout Entrada_2Layout = new javax.swing.GroupLayout(Entrada_2);
        Entrada_2.setLayout(Entrada_2Layout);
        Entrada_2Layout.setHorizontalGroup(
            Entrada_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Entrada_2Layout.setVerticalGroup(
            Entrada_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Dentro_Portal_2Layout = new javax.swing.GroupLayout(Dentro_Portal_2);
        Dentro_Portal_2.setLayout(Dentro_Portal_2Layout);
        Dentro_Portal_2Layout.setHorizontalGroup(
            Dentro_Portal_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Dentro_Portal_2Layout.setVerticalGroup(
            Dentro_Portal_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Salida_2Layout = new javax.swing.GroupLayout(Salida_2);
        Salida_2.setLayout(Salida_2Layout);
        Salida_2Layout.setHorizontalGroup(
            Salida_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Salida_2Layout.setVerticalGroup(
            Salida_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_Portal_LaboratorioLayout = new javax.swing.GroupLayout(Panel_Portal_Laboratorio);
        Panel_Portal_Laboratorio.setLayout(Panel_Portal_LaboratorioLayout);
        Panel_Portal_LaboratorioLayout.setHorizontalGroup(
            Panel_Portal_LaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(Panel_Portal_LaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Portal_LaboratorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Dentro_Portal_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(Salida_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(Entrada_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Panel_Portal_LaboratorioLayout.setVerticalGroup(
            Panel_Portal_LaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(Panel_Portal_LaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Portal_LaboratorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(Panel_Portal_LaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Dentro_Portal_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panel_Portal_LaboratorioLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(Salida_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Entrada_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Panel_Portal_Centro_Comercial.setBackground(new java.awt.Color(156, 28, 156));
        Panel_Portal_Centro_Comercial.setOpaque(false);

        javax.swing.GroupLayout Entrada_3Layout = new javax.swing.GroupLayout(Entrada_3);
        Entrada_3.setLayout(Entrada_3Layout);
        Entrada_3Layout.setHorizontalGroup(
            Entrada_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Entrada_3Layout.setVerticalGroup(
            Entrada_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Dentro_Portal_3Layout = new javax.swing.GroupLayout(Dentro_Portal_3);
        Dentro_Portal_3.setLayout(Dentro_Portal_3Layout);
        Dentro_Portal_3Layout.setHorizontalGroup(
            Dentro_Portal_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Dentro_Portal_3Layout.setVerticalGroup(
            Dentro_Portal_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Salida_3Layout = new javax.swing.GroupLayout(Salida_3);
        Salida_3.setLayout(Salida_3Layout);
        Salida_3Layout.setHorizontalGroup(
            Salida_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Salida_3Layout.setVerticalGroup(
            Salida_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_Portal_Centro_ComercialLayout = new javax.swing.GroupLayout(Panel_Portal_Centro_Comercial);
        Panel_Portal_Centro_Comercial.setLayout(Panel_Portal_Centro_ComercialLayout);
        Panel_Portal_Centro_ComercialLayout.setHorizontalGroup(
            Panel_Portal_Centro_ComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(Panel_Portal_Centro_ComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Portal_Centro_ComercialLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Dentro_Portal_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(Salida_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(Entrada_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Panel_Portal_Centro_ComercialLayout.setVerticalGroup(
            Panel_Portal_Centro_ComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(Panel_Portal_Centro_ComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Portal_Centro_ComercialLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(Panel_Portal_Centro_ComercialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Dentro_Portal_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panel_Portal_Centro_ComercialLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(Salida_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Entrada_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Panel_Portal_Alcantarillado.setBackground(new java.awt.Color(156, 28, 156));
        Panel_Portal_Alcantarillado.setOpaque(false);

        javax.swing.GroupLayout Entrada_4Layout = new javax.swing.GroupLayout(Entrada_4);
        Entrada_4.setLayout(Entrada_4Layout);
        Entrada_4Layout.setHorizontalGroup(
            Entrada_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Entrada_4Layout.setVerticalGroup(
            Entrada_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Dentro_Portal_4.setToolTipText("");

        javax.swing.GroupLayout Dentro_Portal_4Layout = new javax.swing.GroupLayout(Dentro_Portal_4);
        Dentro_Portal_4.setLayout(Dentro_Portal_4Layout);
        Dentro_Portal_4Layout.setHorizontalGroup(
            Dentro_Portal_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Dentro_Portal_4Layout.setVerticalGroup(
            Dentro_Portal_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Salida_4Layout = new javax.swing.GroupLayout(Salida_4);
        Salida_4.setLayout(Salida_4Layout);
        Salida_4Layout.setHorizontalGroup(
            Salida_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        Salida_4Layout.setVerticalGroup(
            Salida_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_Portal_AlcantarilladoLayout = new javax.swing.GroupLayout(Panel_Portal_Alcantarillado);
        Panel_Portal_Alcantarillado.setLayout(Panel_Portal_AlcantarilladoLayout);
        Panel_Portal_AlcantarilladoLayout.setHorizontalGroup(
            Panel_Portal_AlcantarilladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(Panel_Portal_AlcantarilladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Portal_AlcantarilladoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Dentro_Portal_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(Salida_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)
                    .addComponent(Entrada_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Panel_Portal_AlcantarilladoLayout.setVerticalGroup(
            Panel_Portal_AlcantarilladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(Panel_Portal_AlcantarilladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Portal_AlcantarilladoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(Panel_Portal_AlcantarilladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Dentro_Portal_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panel_Portal_AlcantarilladoLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(Salida_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Entrada_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout Panel_Zona_PortalesLayout = new javax.swing.GroupLayout(Panel_Zona_Portales);
        Panel_Zona_Portales.setLayout(Panel_Zona_PortalesLayout);
        Panel_Zona_PortalesLayout.setHorizontalGroup(
            Panel_Zona_PortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Zona_PortalesLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(PORTALES))
            .addGroup(Panel_Zona_PortalesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Panel_Portal_Bosque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Zona_PortalesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Panel_Portal_Laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Zona_PortalesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Panel_Portal_Centro_Comercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Zona_PortalesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Panel_Portal_Alcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_Zona_PortalesLayout.setVerticalGroup(
            Panel_Zona_PortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Zona_PortalesLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(PORTALES)
                .addGap(9, 9, 9)
                .addComponent(Panel_Portal_Bosque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Panel_Portal_Laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Panel_Portal_Centro_Comercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(Panel_Portal_Alcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_Zona_Upsidedown.setBackground(new java.awt.Color(255, 102, 102));
        Panel_Zona_Upsidedown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        Panel_Zona_Upsidedown.setPreferredSize(new java.awt.Dimension(300, 500));

        UPSIDEDOWN.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        UPSIDEDOWN.setText("UPSIDEDOWN");

        Bosque.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Bosque.setText("Bosque");

        Textura_Bosque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Textura_Bosque.jpg"))); // NOI18N

        javax.swing.GroupLayout Panel_BosqueLayout = new javax.swing.GroupLayout(Panel_Bosque);
        Panel_Bosque.setLayout(Panel_BosqueLayout);
        Panel_BosqueLayout.setHorizontalGroup(
            Panel_BosqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BosqueLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ScrollPanel_NiñosBosque, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_BosqueLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(ScrollPanel_DemogorgonsBosque, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Textura_Bosque)
        );
        Panel_BosqueLayout.setVerticalGroup(
            Panel_BosqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Textura_Bosque)
            .addGroup(Panel_BosqueLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_BosqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPanel_NiñosBosque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPanel_DemogorgonsBosque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Laboratorio.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Laboratorio.setText("Laboratorio");

        Textura_Laboratorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Textura_Laboratorio.png"))); // NOI18N

        javax.swing.GroupLayout Panel_Portal_Laboratorio1Layout = new javax.swing.GroupLayout(Panel_Portal_Laboratorio1);
        Panel_Portal_Laboratorio1.setLayout(Panel_Portal_Laboratorio1Layout);
        Panel_Portal_Laboratorio1Layout.setHorizontalGroup(
            Panel_Portal_Laboratorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Portal_Laboratorio1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ScrollPanel_NiñosLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Portal_Laboratorio1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(ScrollPanel_DemogorgonsLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Textura_Laboratorio)
        );
        Panel_Portal_Laboratorio1Layout.setVerticalGroup(
            Panel_Portal_Laboratorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Textura_Laboratorio)
            .addGroup(Panel_Portal_Laboratorio1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_Portal_Laboratorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPanel_NiñosLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPanel_DemogorgonsLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Centro_Comercial.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Centro_Comercial.setText("Centro Comercial");

        Panel_Portal_Centro_Comercial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_Portal_Centro_Comercial1.add(ScrollPanel_NiñosCentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 60));
        Panel_Portal_Centro_Comercial1.add(ScrollPanel_DemogorgonsCentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 90, 60));

        Textura_CentroComercial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Textura_CentroComerical.png"))); // NOI18N
        Panel_Portal_Centro_Comercial1.add(Textura_CentroComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Alcantarillado.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Alcantarillado.setText("Alcantarillado");

        Textura_Alcantarillado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Textura_Alcantarillado.png"))); // NOI18N

        javax.swing.GroupLayout Panel_Portal_Alcantarillado1Layout = new javax.swing.GroupLayout(Panel_Portal_Alcantarillado1);
        Panel_Portal_Alcantarillado1.setLayout(Panel_Portal_Alcantarillado1Layout);
        Panel_Portal_Alcantarillado1Layout.setHorizontalGroup(
            Panel_Portal_Alcantarillado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Portal_Alcantarillado1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(ScrollPanel_DemogorgonsAlcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Panel_Portal_Alcantarillado1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ScrollPanel_NiñosAlcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Textura_Alcantarillado)
        );
        Panel_Portal_Alcantarillado1Layout.setVerticalGroup(
            Panel_Portal_Alcantarillado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Textura_Alcantarillado)
            .addGroup(Panel_Portal_Alcantarillado1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_Portal_Alcantarillado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPanel_DemogorgonsAlcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPanel_NiñosAlcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout Panel_Zona_UpsidedownLayout = new javax.swing.GroupLayout(Panel_Zona_Upsidedown);
        Panel_Zona_Upsidedown.setLayout(Panel_Zona_UpsidedownLayout);
        Panel_Zona_UpsidedownLayout.setHorizontalGroup(
            Panel_Zona_UpsidedownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Zona_UpsidedownLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Panel_Zona_UpsidedownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Bosque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bosque, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Zona_UpsidedownLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(UPSIDEDOWN))
                    .addComponent(Laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Portal_Laboratorio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Centro_Comercial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Portal_Centro_Comercial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alcantarillado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Portal_Alcantarillado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        Panel_Zona_UpsidedownLayout.setVerticalGroup(
            Panel_Zona_UpsidedownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Zona_UpsidedownLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(Panel_Zona_UpsidedownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Zona_UpsidedownLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Panel_Bosque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Zona_UpsidedownLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Bosque))
                    .addComponent(UPSIDEDOWN))
                .addGap(10, 10, 10)
                .addGroup(Panel_Zona_UpsidedownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Laboratorio)
                    .addGroup(Panel_Zona_UpsidedownLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Panel_Portal_Laboratorio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(Panel_Zona_UpsidedownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Centro_Comercial)
                    .addGroup(Panel_Zona_UpsidedownLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Panel_Portal_Centro_Comercial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(Panel_Zona_UpsidedownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alcantarillado)
                    .addGroup(Panel_Zona_UpsidedownLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Panel_Portal_Alcantarillado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        Panel_Estadisticas.setBackground(new java.awt.Color(0, 255, 153));
        Panel_Estadisticas.setOpaque(false);

        Niños_Capturados.setEditable(false);
        Niños_Capturados.setBackground(new java.awt.Color(255, 153, 153));
        Niños_Capturados.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        Niños_Capturados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Niños_Capturados.setText("0");
        Niños_Capturados.setOpaque(true);
        Niños_Capturados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Niños_CapturadosActionPerformed(evt);
            }
        });

        Texto_Eventos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Texto_Eventos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Eventos.setText("Evento Activo:");

        Demogorgon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Demogorgon.png"))); // NOI18N
        Demogorgon.setText("jLabel3");

        Vecna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vecna.png"))); // NOI18N

        Texto_NIÑOS_CAPTURADOS.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Texto_NIÑOS_CAPTURADOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_NIÑOS_CAPTURADOS.setText("Niños capturados");

        Texto_NIÑOS_CAPTURADOS1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Texto_NIÑOS_CAPTURADOS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_NIÑOS_CAPTURADOS1.setText("Ninguno");

        javax.swing.GroupLayout Panel_EstadisticasLayout = new javax.swing.GroupLayout(Panel_Estadisticas);
        Panel_Estadisticas.setLayout(Panel_EstadisticasLayout);
        Panel_EstadisticasLayout.setHorizontalGroup(
            Panel_EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                .addGroup(Panel_EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                        .addComponent(Texto_Eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Texto_NIÑOS_CAPTURADOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addGroup(Panel_EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Texto_NIÑOS_CAPTURADOS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Niños_Capturados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Demogorgon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(Vecna))))
        );
        Panel_EstadisticasLayout.setVerticalGroup(
            Panel_EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Panel_EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                        .addComponent(Texto_NIÑOS_CAPTURADOS)
                        .addGap(9, 9, 9)
                        .addComponent(Niños_Capturados, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Panel_EstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Demogorgon)
                            .addComponent(Vecna)))
                    .addGroup(Panel_EstadisticasLayout.createSequentialGroup()
                        .addComponent(Texto_Eventos)
                        .addGap(9, 9, 9)
                        .addComponent(Texto_NIÑOS_CAPTURADOS1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Texto_Principal.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        Texto_Principal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto_Principal.setText("Simulacion de Stranger Things");
        Texto_Principal.setToolTipText("");

        Boton_Pausa.setText("PAUSAR");
        Boton_Pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PausaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(870, 870, 870)
                .addComponent(Boton_Pausa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Texto_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Panel_Zona_Hawkins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Panel_Zona_Portales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Panel_Zona_Upsidedown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Panel_Estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Boton_Pausa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Texto_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Zona_Hawkins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Zona_Portales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Zona_Upsidedown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(Panel_Estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cantidad_SangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cantidad_SangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cantidad_SangreActionPerformed

    private void Niños_CapturadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Niños_CapturadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Niños_CapturadosActionPerformed

    private void Boton_PausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PausaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_PausaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alcantarillado;
    private javax.swing.JLabel Bosque;
    private javax.swing.JButton Boton_Pausa;
    private javax.swing.JLabel Calle_Principal;
    private javax.swing.JLabel Calle_Principal2;
    private javax.swing.JTextField Cantidad_Sangre;
    private javax.swing.JLabel Centro_Comercial;
    private javax.swing.JLabel Demogorgon;
    private javax.swing.JPanel Dentro_Portal_1;
    private javax.swing.JPanel Dentro_Portal_2;
    private javax.swing.JPanel Dentro_Portal_3;
    private javax.swing.JPanel Dentro_Portal_4;
    private javax.swing.JPanel Entrada_1;
    private javax.swing.JPanel Entrada_2;
    private javax.swing.JPanel Entrada_3;
    private javax.swing.JPanel Entrada_4;
    private javax.swing.JLabel HAWKINS;
    private javax.swing.JLabel Imagen_Hawkins;
    private javax.swing.JLabel Imagen_Radio;
    private javax.swing.JLabel Imagen_Sotano;
    private javax.swing.JLabel Label_SANGRE;
    private javax.swing.JLabel Laboratorio;
    private javax.swing.JTextField Niños_Capturados;
    private javax.swing.JLabel PORTALES;
    private javax.swing.JPanel Panel_Bosque;
    private javax.swing.JPanel Panel_Estadisticas;
    private javax.swing.JPanel Panel_Portal_Alcantarillado;
    private javax.swing.JPanel Panel_Portal_Alcantarillado1;
    private javax.swing.JPanel Panel_Portal_Bosque;
    private javax.swing.JPanel Panel_Portal_Centro_Comercial;
    private javax.swing.JPanel Panel_Portal_Centro_Comercial1;
    private javax.swing.JPanel Panel_Portal_Laboratorio;
    private javax.swing.JPanel Panel_Portal_Laboratorio1;
    private javax.swing.JPanel Panel_Radio_WSQK;
    private javax.swing.JPanel Panel_Zona_Hawkins;
    private javax.swing.JPanel Panel_Zona_Portales;
    private javax.swing.JPanel Panel_Zona_Upsidedown;
    private javax.swing.JPanel Salida_1;
    private javax.swing.JPanel Salida_2;
    private javax.swing.JPanel Salida_3;
    private javax.swing.JPanel Salida_4;
    private javax.swing.JScrollPane ScrollPanel_Calle_Principal;
    private javax.swing.JScrollPane ScrollPanel_DemogorgonsAlcantarillado;
    private javax.swing.JScrollPane ScrollPanel_DemogorgonsBosque;
    private javax.swing.JScrollPane ScrollPanel_DemogorgonsCentroComercial;
    private javax.swing.JScrollPane ScrollPanel_DemogorgonsLaboratorio;
    private javax.swing.JScrollPane ScrollPanel_NiñosAlcantarillado;
    private javax.swing.JScrollPane ScrollPanel_NiñosBosque;
    private javax.swing.JScrollPane ScrollPanel_NiñosCentroComercial;
    private javax.swing.JScrollPane ScrollPanel_NiñosLaboratorio;
    private javax.swing.JScrollPane ScrollPanel_Radio_WSQK;
    private javax.swing.JScrollPane ScrollPanel_Sotano_Byers;
    private javax.swing.JLabel Sotano_Byers;
    private javax.swing.JLabel Texto_Eventos;
    private javax.swing.JLabel Texto_NIÑOS_CAPTURADOS;
    private javax.swing.JLabel Texto_NIÑOS_CAPTURADOS1;
    private javax.swing.JLabel Texto_Principal;
    private javax.swing.JLabel Textura_Alcantarillado;
    private javax.swing.JLabel Textura_Bosque;
    private javax.swing.JLabel Textura_CentroComercial;
    private javax.swing.JLabel Textura_Laboratorio;
    private javax.swing.JLabel UPSIDEDOWN;
    private javax.swing.JLabel Vecna;
    // End of variables declaration//GEN-END:variables
}
