/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Logs;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;

/**
 *
 * @author Alex338
 */
public class VentanaMonitor extends javax.swing.JFrame {
    private Clases.AgrupacionZonas zonas;
    /**
     * Creates new form VentanaMonitor
     */
    public VentanaMonitor() {
        initComponents();
    }
    public VentanaMonitor(Clases.AgrupacionZonas zonas) {
        this.zonas = zonas;
        initComponents();
        javax.swing.Timer timer = new javax.swing.Timer(10, e -> pedirDatosAlServidor());
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoNiñosHawkins = new javax.swing.JLabel();
        PanelUpsidedown = new javax.swing.JPanel();
        UpsideDown1 = new javax.swing.JLabel();
        UpsideDown2 = new javax.swing.JLabel();
        UpsideDown3 = new javax.swing.JLabel();
        UpsideDown4 = new javax.swing.JLabel();
        TituloPortales1 = new java.awt.Label();
        NinosColmena = new javax.swing.JLabel();
        PanelPortales = new javax.swing.JPanel();
        Portal1 = new javax.swing.JLabel();
        Portal2 = new javax.swing.JLabel();
        Portal3 = new javax.swing.JLabel();
        Portal4 = new javax.swing.JLabel();
        TituloPortales = new java.awt.Label();
        PanelEventos = new javax.swing.JPanel();
        TituloEventos = new java.awt.Label();
        TiempoRestanteEvento = new javax.swing.JLabel();
        EventoActivo = new javax.swing.JLabel();
        PanelDemogorgons = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Puntu1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Puntu2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Puntu3 = new javax.swing.JLabel();
        TituloClasificacion = new java.awt.Label();
        Demo1 = new javax.swing.JLabel();
        Demo2 = new javax.swing.JLabel();
        Demo3 = new javax.swing.JLabel();
        Boton_Reanudar = new javax.swing.JButton();
        Boton_Pausa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoNiñosHawkins.setText("Niños totales a salvo en Hawkins: 0");
        getContentPane().add(TextoNiñosHawkins, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 15, 338, 32));

        PanelUpsidedown.setBackground(new java.awt.Color(255, 102, 204));
        PanelUpsidedown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));

        UpsideDown1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpsideDown1.setText("<html><center><b>Zona X - Nombre</b><br>Niños &nbsp;&nbsp;&nbsp;&nbsp; Demos<br>[0] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0]</center></html>");

        UpsideDown2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpsideDown2.setText("<html><center><b>Zona X - Nombre</b><br>Niños &nbsp;&nbsp;&nbsp;&nbsp; Demos<br>[0] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0]</center></html>");

        UpsideDown3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpsideDown3.setText("<html><center><b>Zona X - Nombre</b><br>Niños &nbsp;&nbsp;&nbsp;&nbsp; Demos<br>[0] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0]</center></html>");

        UpsideDown4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpsideDown4.setText("<html><center><b>Zona X - Nombre</b><br>Niños &nbsp;&nbsp;&nbsp;&nbsp; Demos<br>[0] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [0]</center></html>");

        TituloPortales1.setAlignment(java.awt.Label.CENTER);
        TituloPortales1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TituloPortales1.setText("Estado del UpsideDown (niños y Demogorgons)");

        NinosColmena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NinosColmena.setText("Niños en la colmena: XXX");

        javax.swing.GroupLayout PanelUpsidedownLayout = new javax.swing.GroupLayout(PanelUpsidedown);
        PanelUpsidedown.setLayout(PanelUpsidedownLayout);
        PanelUpsidedownLayout.setHorizontalGroup(
            PanelUpsidedownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloPortales1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
            .addComponent(UpsideDown1)
            .addComponent(UpsideDown2)
            .addComponent(UpsideDown3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(UpsideDown4)
            .addComponent(NinosColmena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelUpsidedownLayout.setVerticalGroup(
            PanelUpsidedownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUpsidedownLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TituloPortales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpsideDown1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpsideDown2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpsideDown3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpsideDown4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(NinosColmena)
                .addGap(16, 16, 16))
        );

        getContentPane().add(PanelUpsidedown, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 53, -1, -1));

        PanelPortales.setBackground(new java.awt.Color(255, 153, 153));
        PanelPortales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 2));

        Portal1.setText("<html>\n<div style='text-align: center;'>\n  --- Portal 1 (Bosque) ---<br>\n  Hawkins → UpsideDown | CRUZANDO | UpsideDown → Hawkins<br>\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;[0]&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0]\n</div>\n</html>");

        Portal2.setText("<html>\n<div style='text-align: center;'>\n  --- Portal 2 (Laboratorio) ---<br>\n  Hawkins → UpsideDown | CRUZANDO | UpsideDown → Hawkins<br>\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;[0]&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0]\n</div>\n</html>");

        Portal3.setText("<html>\n<div style='text-align: center;'>\n  --- Portal 3 (Centro Comercial) ---<br>\n  Hawkins → UpsideDown | CRUZANDO | UpsideDown → Hawkins<br>\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;[0]&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0]\n</div>\n</html>");

        Portal4.setText("<html>\n<div style='text-align: center;'>\n  --- Portal 4 (Alcantarillado) ---<br>\n  Hawkins → UpsideDown | CRUZANDO | UpsideDown → Hawkins<br>\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;[0]&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0]\n</div>\n</html>");

        TituloPortales.setAlignment(java.awt.Label.CENTER);
        TituloPortales.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TituloPortales.setText("Estado de los Portales (niños)");

        javax.swing.GroupLayout PanelPortalesLayout = new javax.swing.GroupLayout(PanelPortales);
        PanelPortales.setLayout(PanelPortalesLayout);
        PanelPortalesLayout.setHorizontalGroup(
            PanelPortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloPortales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelPortalesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelPortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Portal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Portal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Portal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Portal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelPortalesLayout.setVerticalGroup(
            PanelPortalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPortalesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TituloPortales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Portal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(Portal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(Portal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(Portal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        getContentPane().add(PanelPortales, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 53, -1, -1));

        PanelEventos.setBackground(new java.awt.Color(204, 255, 204));
        PanelEventos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 2));

        TituloEventos.setAlignment(java.awt.Label.CENTER);
        TituloEventos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TituloEventos.setText("Eventos");

        TiempoRestanteEvento.setText("Tiempo restante del evento: 0");

        EventoActivo.setText("Evento Activo: Sin evento activo.");

        javax.swing.GroupLayout PanelEventosLayout = new javax.swing.GroupLayout(PanelEventos);
        PanelEventos.setLayout(PanelEventosLayout);
        PanelEventosLayout.setHorizontalGroup(
            PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelEventosLayout.createSequentialGroup()
                .addGroup(PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEventosLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(EventoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEventosLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(TiempoRestanteEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PanelEventosLayout.setVerticalGroup(
            PanelEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEventosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(TituloEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EventoActivo)
                .addGap(18, 18, 18)
                .addComponent(TiempoRestanteEvento)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(PanelEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        PanelDemogorgons.setBackground(new java.awt.Color(255, 255, 102));
        PanelDemogorgons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        Puntu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Puntu1.setText("DXXXX");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Puntu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Puntu1)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        Puntu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Puntu2.setText("DXXXX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Puntu2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Puntu2)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 153, 0));

        Puntu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Puntu3.setText("DXXXX");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Puntu3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Puntu3)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        TituloClasificacion.setAlignment(java.awt.Label.CENTER);
        TituloClasificacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TituloClasificacion.setText("Clasificación Demogorgons");

        Demo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Demo1.setText("DXXXX");

        Demo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Demo2.setText("Demo2");

        Demo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Demo3.setText("Demo3");

        javax.swing.GroupLayout PanelDemogorgonsLayout = new javax.swing.GroupLayout(PanelDemogorgons);
        PanelDemogorgons.setLayout(PanelDemogorgonsLayout);
        PanelDemogorgonsLayout.setHorizontalGroup(
            PanelDemogorgonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDemogorgonsLayout.createSequentialGroup()
                .addGroup(PanelDemogorgonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDemogorgonsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloClasificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                    .addGroup(PanelDemogorgonsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelDemogorgonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Demo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelDemogorgonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Demo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelDemogorgonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Demo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );
        PanelDemogorgonsLayout.setVerticalGroup(
            PanelDemogorgonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDemogorgonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(PanelDemogorgonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDemogorgonsLayout.createSequentialGroup()
                        .addComponent(Demo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDemogorgonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDemogorgonsLayout.createSequentialGroup()
                                .addComponent(Demo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelDemogorgonsLayout.createSequentialGroup()
                        .addComponent(Demo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(PanelDemogorgons, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 380, -1));

        Boton_Reanudar.setText("REANUDAR");
        Boton_Reanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ReanudarActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Reanudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 130, 50));

        Boton_Pausa.setText("PAUSAR");
        Boton_Pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PausaActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Pausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, 130, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_ReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ReanudarActionPerformed
        // TODO add your handling code here:
        if (zonas != null) {
            zonas.reanudar();
            System.out.println("Simulación reanudada.");
            Logs.getInstance().log("SIMULACIÓN REANUDADA");
        }
    }//GEN-LAST:event_Boton_ReanudarActionPerformed

    private void Boton_PausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PausaActionPerformed
        // TODO add your handling code here:
        if (zonas != null) {
            zonas.pausar();
            System.out.println("Simulación pausada.");
            Logs.getInstance().log("SIMULACIÓN PARADA");
        }
    }//GEN-LAST:event_Boton_PausaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void actualizarLabelPortal(javax.swing.JLabel label, String nombre, String datosRaw) {

    String[] d = datosRaw.split(",");
    

    if (d.length < 3) return;

    String html = "<html>" +
                  "<div style='text-align: center; font-family: monospaced;'>" +
                  "  --- Portal (" + nombre + ") ---<br>" +
                  "  Hawkins → UpsideDown | CRUZANDO | UpsideDown → Hawkins<br>" +
                  "  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[" + d[0] + "]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | " +
                  "&nbsp;&nbsp;[" + d[1] + "]&nbsp;&nbsp; | " +
                  "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[" + d[2] + "]" +
                  "</div>" +
                  "</html>";
    
    label.setText(html);
    }
    private void actualizarLabelZona(javax.swing.JLabel label, int num, String nombre, String datosRaw) {
    String[] d = datosRaw.split("/");
    if (d.length < 2) return;

    String html = "<html>" +
                  "<center>" +
                  "  <b style='color: #FF0000;'>Zona " + num + " - " + nombre + "</b><br>" +
                  "  Niños &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Demogorgons<br>" +
                  "  <font size='5'>[" + d[0] + "] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [" + d[1] + "]</font>" +
                  "</center>" +
                  "</html>";
    
    label.setText(html);
    label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); 
}
    private void actualizarRanking(String datosTop) {

    if (datosTop.equals("No hay datos") || datosTop.equals("Sin capturas")) {
        Demo1.setText("-"); Puntu1.setText("0");
        Demo2.setText("-"); Puntu2.setText("0");
        Demo3.setText("-"); Puntu3.setText("0");
        return;
    }

    String[] tops = datosTop.split(" \\| ");

    javax.swing.JLabel[] labelsNombres = {Demo1, Demo2, Demo3};
    javax.swing.JLabel[] labelsPuntos = {Puntu1, Puntu2, Puntu3};

    for (int i = 0; i < 3; i++) {
        if (i < tops.length) {
            String[] info = tops[i].split(": "); 
            if (info.length == 2) {
                labelsNombres[i].setText(info[0]);
                labelsPuntos[i].setText(info[1]);
            }
        } else {
            labelsNombres[i].setText("-");
            labelsPuntos[i].setText("0");
        }
    }
}
    private void pedirDatosAlServidor() {
    try (Socket s = new Socket("localhost", 5011)) { 
        DataOutputStream salida = new DataOutputStream(s.getOutputStream());
        DataInputStream entrada = new DataInputStream(s.getInputStream());

        salida.writeUTF("GET_DATA");
        String respuesta = entrada.readUTF();
        String[] partes = respuesta.split(";");

        if (partes.length >= 13) {
            //Actualizar Resto de partes
            TextoNiñosHawkins.setText("Total niños en Hawkins: " + partes[0]);
            EventoActivo.setText("Evento Activo: " + partes[1]);
            TiempoRestanteEvento.setText("Tiempo restante del evento " + partes[2]);
            NinosColmena.setText("Niños en la colmena: "+ partes[3]);
            //Actualizar Portales
            actualizarLabelPortal(Portal1, "Bosque", partes[4]);
            actualizarLabelPortal(Portal2, "Laboratorio", partes[5]);
            actualizarLabelPortal(Portal3, "Centro Comercial", partes[6]);
            actualizarLabelPortal(Portal4, "Alcantarillado", partes[7]);
            //Actualizar Zonas Upside Down (partes 8 a 11)
            actualizarLabelZona(UpsideDown1, 1, "Bosque", partes[8]);
            actualizarLabelZona(UpsideDown2, 2, "Laboratorio", partes[9]);
            actualizarLabelZona(UpsideDown3, 3, "Centro Comercial", partes[10]);
            actualizarLabelZona(UpsideDown4, 4, "Alcantarillado", partes[11]);
            //Actualizar Ranking
            actualizarRanking(partes[12]);
        }
    } catch (Exception ex) {

    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMonitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Pausa;
    private javax.swing.JButton Boton_Reanudar;
    private javax.swing.JLabel Demo1;
    private javax.swing.JLabel Demo2;
    private javax.swing.JLabel Demo3;
    private javax.swing.JLabel EventoActivo;
    private javax.swing.JLabel NinosColmena;
    private javax.swing.JPanel PanelDemogorgons;
    private javax.swing.JPanel PanelEventos;
    private javax.swing.JPanel PanelPortales;
    private javax.swing.JPanel PanelUpsidedown;
    private javax.swing.JLabel Portal1;
    private javax.swing.JLabel Portal2;
    private javax.swing.JLabel Portal3;
    private javax.swing.JLabel Portal4;
    private javax.swing.JLabel Puntu1;
    private javax.swing.JLabel Puntu2;
    private javax.swing.JLabel Puntu3;
    private javax.swing.JLabel TextoNiñosHawkins;
    private javax.swing.JLabel TiempoRestanteEvento;
    private java.awt.Label TituloClasificacion;
    private java.awt.Label TituloEventos;
    private java.awt.Label TituloPortales;
    private java.awt.Label TituloPortales1;
    private javax.swing.JLabel UpsideDown1;
    private javax.swing.JLabel UpsideDown2;
    private javax.swing.JLabel UpsideDown3;
    private javax.swing.JLabel UpsideDown4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
